/**
 * =============================================
 * DADOS DOS ELEMENTOS QUÍMICOS - PARTE 3
 * Metais de Transição (8-12), Lantanídeos e Actinídeos
 * + Configurações do Sistema
 * =============================================
 * 
 * INSTRUÇÕES:
 * 1. Salve este arquivo como: data3.js
 * 2. Coloque na mesma pasta que index.html, data.js e data2.js
 * 3. Este é o ÚLTIMO arquivo de dados
 * 4. Certifique-se que está em UTF-8
 */

Object.assign(FAMILIES_DATA, {

    'metais-transicao-ferro': {
        name: 'Série do Ferro',
        group: 8,
        icon: '🔨',
        multiGroup: true,
        elements: [
            { number: 26, symbol: 'Fe', name: 'Ferro', mass: '55.845', period: 4, group: 8,
              description: 'Metal mais usado pela humanidade. Essencial para aço.',
              properties: 'Metal cinza prateado, maleável e magnético.',
              discovery: 'Usado desde a pré-história.' },
            { number: 27, symbol: 'Co', name: 'Cobalto', mass: '58.933', period: 4, group: 9,
              description: 'Usado em baterias de lítio-íon e pigmentos azuis.',
              properties: 'Metal duro, ferromagnético, azul-acinzentado.',
              discovery: 'Descoberto em 1735 por Georg Brandt.' },
            { number: 28, symbol: 'Ni', name: 'Níquel', mass: '58.693', period: 4, group: 10,
              description: 'Usado em aço inoxidável, baterias e moedas.',
              properties: 'Metal prateado duro e maleável. Magnético.',
              discovery: 'Isolado em 1751 por Axel Fredrik Cronstedt.' }
        ]
    },

    'metais-cunhagem': {
        name: 'Metais de Cunhagem',
        group: 11,
        icon: '💰',
        elements: [
            { number: 29, symbol: 'Cu', name: 'Cobre', mass: '63.546', period: 4, group: 11,
              description: 'Excelente condutor. Usado em fios, tubulações e moedas.',
              properties: 'Metal avermelhado, maleável e dúctil.',
              discovery: 'Usado desde 8000 a.C.' },
            { number: 47, symbol: 'Ag', name: 'Prata', mass: '107.868', period: 5, group: 11,
              description: 'Melhor condutor elétrico. Usado em joias e eletrônicos.',
              properties: 'Metal branco brilhante, maleável e dúctil.',
              discovery: 'Conhecida desde a antiguidade.' },
            { number: 79, symbol: 'Au', name: 'Ouro', mass: '196.967', period: 6, group: 11,
              description: 'Metal precioso. Usado em joias, reservas financeiras e eletrônicos.',
              properties: 'Metal amarelo brilhante. Não oxida ou corrói.',
              discovery: 'Usado desde a pré-história.' }
        ]
    },

    'grupo-zinco': {
        name: 'Grupo do Zinco',
        group: 12,
        icon: '⚗️',
        elements: [
            { number: 30, symbol: 'Zn', name: 'Zinco', mass: '65.38', period: 4, group: 12,
              description: 'Usado em galvanização, baterias e como nutriente.',
              properties: 'Metal azul-prateado, moderadamente reativo.',
              discovery: 'Isolado em 1746 por Andreas Marggraf.' },
            { number: 48, symbol: 'Cd', name: 'Cádmio', mass: '112.411', period: 5, group: 12,
              description: 'Usado em baterias e pigmentos. Tóxico.',
              properties: 'Metal prateado-azulado, macio.',
              discovery: 'Descoberto em 1817 por Friedrich Stromeyer.' },
            { number: 80, symbol: 'Hg', name: 'Mercúrio', mass: '200.59', period: 6, group: 12,
              description: 'Único metal líquido à temperatura ambiente.',
              properties: 'Metal prateado líquido. Tóxico.',
              discovery: 'Conhecido desde a antiguidade.' }
        ]
    },

    'metais-platina': {
        name: 'Metais da Platina',
        group: 10,
        icon: '💍',
        multiGroup: true,
        elements: [
            { number: 44, symbol: 'Ru', name: 'Rutênio', mass: '101.07', period: 5, group: 8,
              description: 'Usado em catalisadores e contatos elétricos.',
              properties: 'Metal branco prateado duro e raro.',
              discovery: 'Descoberto em 1844 por Karl Ernst Claus.' },
            { number: 45, symbol: 'Rh', name: 'Ródio', mass: '102.906', period: 5, group: 9,
              description: 'Metal mais caro. Usado em catalisadores automotivos.',
              properties: 'Metal branco prateado, altamente reflexivo.',
              discovery: 'Descoberto em 1803 por William Hyde Wollaston.' },
            { number: 46, symbol: 'Pd', name: 'Paládio', mass: '106.42', period: 5, group: 10,
              description: 'Usado em catalisadores, eletrônicos e joias.',
              properties: 'Metal branco prateado maleável.',
              discovery: 'Descoberto em 1803 por William Hyde Wollaston.' },
            { number: 76, symbol: 'Os', name: 'Ósmio', mass: '190.23', period: 6, group: 8,
              description: 'Metal mais denso. Usado em ligas de alta resistência.',
              properties: 'Metal azul-acinzentado denso. Densidade: 22,59 g/cm³.',
              discovery: 'Descoberto em 1803 por Smithson Tennant.' },
            { number: 77, symbol: 'Ir', name: 'Irídio', mass: '192.217', period: 6, group: 9,
              description: 'Segundo metal mais denso. Usado em velas de ignição.',
              properties: 'Metal branco prateado duro e quebradiço.',
              discovery: 'Descoberto em 1803 por Smithson Tennant.' },
            { number: 78, symbol: 'Pt', name: 'Platina', mass: '195.084', period: 6, group: 10,
              description: 'Metal precioso. Usado em catalisadores, joias e medicina.',
              properties: 'Metal branco prateado denso. Não oxida.',
              discovery: 'Conhecida por povos pré-colombianos.' }
        ]
    },

    'lantanideos': {
        name: 'Lantanídeos (Terras Raras)',
        group: 'Ln',
        icon: '🌟',
        multiGroup: true,
        elements: [
            { number: 57, symbol: 'La', name: 'Lantânio', mass: '138.905', period: 6, group: 3,
              description: 'Usado em lentes de câmeras e baterias híbridas.',
              properties: 'Metal prateado macio. Oxida rapidamente.',
              discovery: 'Descoberto em 1839 por Carl Gustaf Mosander.' },
            { number: 58, symbol: 'Ce', name: 'Cério', mass: '140.116', period: 6, group: 3,
              description: 'Terra rara mais abundante. Usado em catalisadores.',
              properties: 'Metal prateado macio e dúctil.',
              discovery: 'Descoberto em 1803.' },
            { number: 59, symbol: 'Pr', name: 'Praseodímio', mass: '140.908', period: 6, group: 3,
              description: 'Usado em ímãs permanentes e lentes.',
              properties: 'Metal prateado macio e maleável.',
              discovery: 'Descoberto em 1885.' },
            { number: 60, symbol: 'Nd', name: 'Neodímio', mass: '144.242', period: 6, group: 3,
              description: 'Usado em ímãs super potentes e lasers.',
              properties: 'Metal prateado brilhante.',
              discovery: 'Descoberto em 1885.' },
            { number: 61, symbol: 'Pm', name: 'Promécio', mass: '145', period: 6, group: 3,
              description: 'Elemento radioativo. Usado em baterias nucleares.',
              properties: 'Metal radioativo.',
              discovery: 'Sintetizado em 1945.' },
            { number: 62, symbol: 'Sm', name: 'Samário', mass: '150.36', period: 6, group: 3,
              description: 'Usado em ímãs permanentes e lasers.',
              properties: 'Metal prateado moderadamente duro.',
              discovery: 'Descoberto em 1879.' },
            { number: 63, symbol: 'Eu', name: 'Európio', mass: '151.964', period: 6, group: 3,
              description: 'Usado em fósforos de telas de TV e LEDs.',
              properties: 'Metal prateado macio.',
              discovery: 'Descoberto em 1901.' },
            { number: 64, symbol: 'Gd', name: 'Gadolínio', mass: '157.25', period: 6, group: 3,
              description: 'Usado em ressonância magnética e ímãs.',
              properties: 'Metal prateado maleável.',
              discovery: 'Descoberto em 1880.' },
            { number: 65, symbol: 'Tb', name: 'Térbio', mass: '158.925', period: 6, group: 3,
              description: 'Usado em fósforos verdes e lasers.',
              properties: 'Metal prateado macio.',
              discovery: 'Descoberto em 1843.' },
            { number: 66, symbol: 'Dy', name: 'Disprósio', mass: '162.500', period: 6, group: 3,
              description: 'Usado em lasers e ímãs permanentes.',
              properties: 'Metal prateado brilhante.',
              discovery: 'Descoberto em 1886.' },
            { number: 67, symbol: 'Ho', name: 'Hólmio', mass: '164.930', period: 6, group: 3,
              description: 'Usado em lasers médicos e ímãs.',
              properties: 'Metal prateado macio.',
              discovery: 'Descoberto em 1878.' },
            { number: 68, symbol: 'Er', name: 'Érbio', mass: '167.259', period: 6, group: 3,
              description: 'Usado em fibras ópticas e lasers.',
              properties: 'Metal prateado macio.',
              discovery: 'Descoberto em 1843.' },
            { number: 69, symbol: 'Tm', name: 'Túlio', mass: '168.934', period: 6, group: 3,
              description: 'Segundo elemento mais raro das terras raras.',
              properties: 'Metal prateado macio.',
              discovery: 'Descoberto em 1879.' },
            { number: 70, symbol: 'Yb', name: 'Itérbio', mass: '173.045', period: 6, group: 3,
              description: 'Usado em lasers e relógios atômicos.',
              properties: 'Metal prateado macio.',
              discovery: 'Descoberto em 1878.' },
            { number: 71, symbol: 'Lu', name: 'Lutécio', mass: '174.967', period: 6, group: 3,
              description: 'Terra rara mais cara.',
              properties: 'Metal prateado duro e denso.',
              discovery: 'Descoberto em 1907.' }
        ]
    },

    'actinideos': {
        name: 'Actinídeos (Radioativos)',
        group: 'An',
        icon: '☢️',
        multiGroup: true,
        elements: [
            { number: 89, symbol: 'Ac', name: 'Actínio', mass: '227', period: 7, group: 3,
              description: 'Elemento radioativo. Usado em geradores de nêutrons.',
              properties: 'Metal prateado radioativo. Brilha no escuro com luz azul pálida.',
              discovery: 'Descoberto em 1899 por André-Louis Debierne.' },
            { number: 90, symbol: 'Th', name: 'Tório', mass: '232.038', period: 7, group: 3,
              description: 'Usado em lâmpadas de gás e reatores nucleares. Potencial combustível nuclear.',
              properties: 'Metal radioativo prateado. Mais abundante que urânio.',
              discovery: 'Descoberto em 1828 por Jöns Jacob Berzelius.' },
            { number: 91, symbol: 'Pa', name: 'Protactínio', mass: '231.036', period: 7, group: 3,
              description: 'Elemento radioativo raro. Pouco uso prático além de pesquisa.',
              properties: 'Metal prateado brilhante radioativo. Extremamente raro.',
              discovery: 'Descoberto em 1913 por Kasimir Fajans e Oswald Helmuth Göhring.' },
            { number: 92, symbol: 'U', name: 'Urânio', mass: '238.029', period: 7, group: 3,
              description: 'Combustível nuclear principal. Usado em reatores e armas nucleares.',
              properties: 'Metal prateado denso e radioativo. Último elemento natural abundante.',
              discovery: 'Descoberto em 1789 por Martin Heinrich Klaproth.' },
            { number: 93, symbol: 'Np', name: 'Netúnio', mass: '237', period: 7, group: 3,
              description: 'Primeiro elemento transurânico. Usado em detectores de nêutrons.',
              properties: 'Metal prateado radioativo. Primeiro elemento sintético descoberto.',
              discovery: 'Sintetizado em 1940 por Edwin McMillan e Philip H. Abelson.' },
            { number: 94, symbol: 'Pu', name: 'Plutônio', mass: '244', period: 7, group: 3,
              description: 'Usado em armas nucleares, reatores e geradores espaciais.',
              properties: 'Metal prateado radioativo. Quente ao toque devido à radioatividade.',
              discovery: 'Sintetizado em 1940 por Glenn T. Seaborg, Edwin McMillan, Joseph W. Kennedy e Arthur Wahl.' },
            { number: 95, symbol: 'Am', name: 'Amerício', mass: '243', period: 7, group: 3,
              description: 'Usado em detectores de fumaça domésticos e equipamentos de medição industrial.',
              properties: 'Metal prateado radioativo. Emite radiação alfa e gama.',
              discovery: 'Sintetizado em 1944 por Glenn T. Seaborg, Ralph A. James, Leon O. Morgan e Albert Ghiorso.' },
            { number: 96, symbol: 'Cm', name: 'Cúrio', mass: '247', period: 7, group: 3,
              description: 'Usado em geradores termoelétricos de radioisótopos para sondas espaciais.',
              properties: 'Metal prateado radioativo. Brilha no escuro devido à intensa radioatividade.',
              discovery: 'Sintetizado em 1944 por Glenn T. Seaborg, Ralph A. James e Albert Ghiorso.' },
            { number: 97, symbol: 'Bk', name: 'Berquélio', mass: '247', period: 7, group: 3,
              description: 'Usado apenas em pesquisas científicas. Elemento extremamente raro.',
              properties: 'Metal prateado radioativo. Produzido em quantidades muito pequenas.',
              discovery: 'Sintetizado em 1949 por Glenn T. Seaborg, Stanley G. Thompson e Albert Ghiorso.' },
            { number: 98, symbol: 'Cf', name: 'Califórnio', mass: '251', period: 7, group: 3,
              description: 'Usado em tratamento de câncer, detectores de metais em aeroportos e análise de minerais.',
              properties: 'Metal prateado radioativo. Forte emissor de nêutrons.',
              discovery: 'Sintetizado em 1950 por Stanley G. Thompson, Kenneth Street Jr., Albert Ghiorso e Glenn T. Seaborg.' },
            { number: 99, symbol: 'Es', name: 'Einstênio', mass: '252', period: 7, group: 3,
              description: 'Elemento sintético usado apenas em pesquisas. Descoberto em resíduos de teste nuclear.',
              properties: 'Metal prateado radioativo. Extremamente instável e raro.',
              discovery: 'Descoberto em 1952 por Albert Ghiorso e colaboradores nos resíduos do teste nuclear Ivy Mike.' },
            { number: 100, symbol: 'Fm', name: 'Férmio', mass: '257', period: 7, group: 3,
              description: 'Elemento sintético extremamente raro. Usado apenas em pesquisas científicas.',
              properties: 'Metal radioativo. Produzido em quantidades microscópicas.',
              discovery: 'Descoberto em 1952 por Albert Ghiorso e colaboradores nos resíduos do teste nuclear Ivy Mike.' },
            { number: 101, symbol: 'Md', name: 'Mendelévio', mass: '258', period: 7, group: 3,
              description: 'Elemento sintético. Nomeado em homenagem a Dmitri Mendeleev, criador da tabela periódica.',
              properties: 'Metal radioativo. Meia-vida muito curta.',
              discovery: 'Sintetizado em 1955 por Albert Ghiorso, Glenn T. Seaborg, Gregory R. Choppin, Bernard G. Harvey e Stanley G. Thompson.' },
            { number: 102, symbol: 'No', name: 'Nobélio', mass: '259', period: 7, group: 3,
              description: 'Elemento sintético. Nomeado em homenagem a Alfred Nobel.',
              properties: 'Metal radioativo. Produzido átomo por átomo.',
              discovery: 'Sintetizado em 1958 por Albert Ghiorso, Glenn T. Seaborg, Torbjørn Sikkeland e John R. Walton.' },
            { number: 103, symbol: 'Lr', name: 'Laurêncio', mass: '266', period: 7, group: 3,
              description: 'Último actinídeo. Nomeado em homenagem a Ernest O. Lawrence, inventor do ciclotron.',
              properties: 'Metal radioativo. Último elemento da série dos actinídeos.',
              discovery: 'Sintetizado em 1961 por Albert Ghiorso, Torbjørn Sikkeland, Almon E. Larsh e Robert M. Latimer.' }
        ]
    },

    'hidrogenio': {
        name: 'Hidrogênio',
        group: 'H',
        icon: '🎈',
        multiGroup: true,
        elements: [
            { number: 1, symbol: 'H', name: 'Hidrogênio', mass: '1.008', period: 1, group: 1,
              description: 'Elemento mais abundante no universo. Combustível das estrelas. Usado em fertilizantes, refinarias e células de combustível.',
              properties: 'Gás incolor, inodoro e altamente inflamável. Mais leve que o ar.',
              discovery: 'Identificado como elemento em 1766 por Henry Cavendish.' }
        ]
    },

    'periodo7-transicao': {
        name: 'Metais de Transição - Período 7',
        group: 'P7',
        icon: '🔬',
        multiGroup: true,
        elements: [
            { number: 104, symbol: 'Rf', name: 'Rutherfórdio', mass: '267', period: 7, group: 4,
              description: 'Elemento sintético radioativo. Usado apenas em pesquisas.',
              properties: 'Metal de transição radioativo. Extremamente instável.',
              discovery: 'Sintetizado em 1969 por Albert Ghiorso e colaboradores.' },
            { number: 105, symbol: 'Db', name: 'Dúbnio', mass: '268', period: 7, group: 5,
              description: 'Elemento sintético radioativo. Nomeado em homenagem a Dubna, Rússia.',
              properties: 'Metal de transição radioativo. Meia-vida muito curta.',
              discovery: 'Sintetizado em 1970 por equipes em Dubna e Berkeley.' },
            { number: 106, symbol: 'Sg', name: 'Seabórgio', mass: '269', period: 7, group: 6,
              description: 'Elemento sintético. Nomeado em homenagem a Glenn T. Seaborg.',
              properties: 'Metal de transição radioativo.',
              discovery: 'Sintetizado em 1974 por Albert Ghiorso e colaboradores.' },
            { number: 107, symbol: 'Bh', name: 'Bóhrio', mass: '270', period: 7, group: 7,
              description: 'Elemento sintético. Nomeado em homenagem a Niels Bohr.',
              properties: 'Metal de transição radioativo.',
              discovery: 'Sintetizado em 1981 por Peter Armbruster e Gottfried Münzenberg.' },
            { number: 108, symbol: 'Hs', name: 'Hássio', mass: '277', period: 7, group: 8,
              description: 'Elemento sintético. Nomeado em homenagem ao estado alemão de Hesse.',
              properties: 'Metal de transição radioativo.',
              discovery: 'Sintetizado em 1984 por Peter Armbruster e Gottfried Münzenberg.' },
            { number: 109, symbol: 'Mt', name: 'Meitnério', mass: '278', period: 7, group: 9,
              description: 'Elemento sintético. Nomeado em homenagem a Lise Meitner.',
              properties: 'Metal de transição radioativo.',
              discovery: 'Sintetizado em 1982 por Peter Armbruster e Gottfried Münzenberg.' },
            { number: 110, symbol: 'Ds', name: 'Darmstádtio', mass: '281', period: 7, group: 10,
              description: 'Elemento sintético. Nomeado em homenagem a Darmstadt, Alemanha.',
              properties: 'Metal de transição radioativo.',
              discovery: 'Sintetizado em 1994 por Sigurd Hofmann e colaboradores.' },
            { number: 111, symbol: 'Rg', name: 'Roentgênio', mass: '282', period: 7, group: 11,
              description: 'Elemento sintético. Nomeado em homenagem a Wilhelm Röntgen.',
              properties: 'Metal de transição radioativo.',
              discovery: 'Sintetizado em 1994 por Sigurd Hofmann e colaboradores.' },
            { number: 112, symbol: 'Cn', name: 'Copernício', mass: '285', period: 7, group: 12,
              description: 'Elemento sintético. Nomeado em homenagem a Nicolau Copérnico.',
              properties: 'Metal de transição radioativo. Possivelmente líquido ou gasoso.',
              discovery: 'Sintetizado em 1996 por Sigurd Hofmann e colaboradores.' },
            { number: 113, symbol: 'Nh', name: 'Nihônio', mass: '286', period: 7, group: 13,
              description: 'Elemento sintético. Nomeado em homenagem ao Japão (Nihon).',
              properties: 'Metal radioativo. Primeiro elemento sintetizado na Ásia.',
              discovery: 'Sintetizado em 2003 por equipe do RIKEN, Japão.' },
            { number: 114, symbol: 'Fl', name: 'Fleróvio', mass: '289', period: 7, group: 14,
              description: 'Elemento sintético. Nomeado em homenagem a Georgy Flyorov.',
              properties: 'Metal radioativo. Possivelmente mais estável que vizinhos.',
              discovery: 'Sintetizado em 1998 por equipe em Dubna, Rússia.' },
            { number: 115, symbol: 'Mc', name: 'Moscóvio', mass: '290', period: 7, group: 15,
              description: 'Elemento sintético. Nomeado em homenagem a Moscou.',
              properties: 'Metal radioativo.',
              discovery: 'Sintetizado em 2003 por equipe russo-americana.' },
            { number: 116, symbol: 'Lv', name: 'Livermório', mass: '293', period: 7, group: 16,
              description: 'Elemento sintético. Nomeado em homenagem ao Laboratório Lawrence Livermore.',
              properties: 'Metal radioativo.',
              discovery: 'Sintetizado em 2000 por equipe russo-americana.' },
            { number: 117, symbol: 'Ts', name: 'Tenessino', mass: '294', period: 7, group: 17,
              description: 'Elemento sintético. Nomeado em homenagem ao estado do Tennessee.',
              properties: 'Possivelmente um semimetal radioativo.',
              discovery: 'Sintetizado em 2010 por equipe russo-americana.' },
            { number: 118, symbol: 'Og', name: 'Oganessônio', mass: '294', period: 7, group: 18,
              description: 'Elemento mais pesado confirmado. Nomeado em homenagem a Yuri Oganessian.',
              properties: 'Possivelmente um gás nobre radioativo. Último elemento da tabela periódica.',
              discovery: 'Sintetizado em 2002 por equipe em Dubna, Rússia.' }
        ]
    }
});

/**
 * Estrutura da Tabela Periódica
 */
const TABLE_STRUCTURE = [
    [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 18],
    [1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 13, 14, 15, 16, 17, 18],
    [1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 13, 14, 15, 16, 17, 18],
    [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18],
    [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18],
    [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18],
    [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]
];

/**
 * Configurações de dicas por grupo
 */
const HINTS_CONFIG = {
    18: { title: 'Gases Nobres', tips: ['Última coluna (grupo 18)', 'Estáveis e inertes', 'He período 1, Rn período 6'] },
    1: { title: 'Metais Alcalinos', tips: ['Primeira coluna (grupo 1)', 'Muito reativos com água', 'Li período 2, Fr período 7'] },
    2: { title: 'Metais Alcalino-Terrosos', tips: ['Segunda coluna (grupo 2)', 'Menos reativos que alcalinos', 'Be período 2, Ra período 7'] },
    17: { title: 'Halogênios', tips: ['Penúltima coluna (grupo 17)', 'Formadores de sais', 'F período 2, At período 6'] },
    16: { title: 'Calcogênios', tips: ['Grupo 16', 'Incluem o oxigênio', 'O período 2, Po período 6'] },
    15: { title: 'Família do Nitrogênio', tips: ['Grupo 15', 'N forma 78% do ar', 'N período 2, Bi período 6'] },
    14: { title: 'Família do Carbono', tips: ['Grupo 14', 'Base da vida orgânica', 'C período 2, Pb período 6'] },
    13: { title: 'Família do Boro', tips: ['Grupo 13', 'Al é o metal mais abundante', 'B período 2, Tl período 6'] },
    3: { title: 'Grupo do Escândio', tips: ['Grupo 3', 'Metais de transição leves', 'Sc período 4, Y período 5'] },
    4: { title: 'Grupo do Titânio', tips: ['Grupo 4', 'Metais resistentes', 'Ti período 4, Hf período 6'] },
    5: { title: 'Grupo do Vanádio', tips: ['Grupo 5', 'Usados em ligas', 'V período 4, Ta período 6'] },
    6: { title: 'Grupo do Cromo', tips: ['Grupo 6', 'W tem maior ponto de fusão', 'Cr período 4, W período 6'] },
    7: { title: 'Grupo do Manganês', tips: ['Grupo 7', 'Tc foi o primeiro artificial', 'Mn período 4, Re período 6'] },
    11: { title: 'Metais de Cunhagem', tips: ['Grupo 11', 'Metais preciosos', 'Cu período 4, Au período 6'] },
    12: { title: 'Grupo do Zinco', tips: ['Grupo 12', 'Hg é líquido à temp. ambiente', 'Zn período 4, Hg período 6'] },
    'Ln': { title: 'Lantanídeos', tips: ['Terras raras', 'Período 6', 'La (57) até Lu (71)', '15 elementos'] },
    'An': { title: 'Actinídeos', tips: ['Elementos radioativos', 'Período 7', 'Ac (89) até Lr (103)', '15 elementos'] },
    'P7': { title: 'Período 7 - Sintéticos', tips: ['Elementos super-pesados', 'Todos radioativos', 'Rf (104) até Og (118)', 'Organize por número atômico crescente'] },
    'H': { title: 'Hidrogênio', tips: ['Elemento mais leve', 'Mais abundante no universo', 'Grupo 1, Período 1'] },
    'multi': { title: 'Múltiplos Grupos', tips: ['Metais de transição', 'Observe período e grupo', 'Número atômico crescente'] }
};
